ALTER TYPE "InvoiceDocumentType" ADD VALUE IF NOT EXISTS 'CONSUMER_02';
ALTER TYPE "InvoiceDocumentType" ADD VALUE IF NOT EXISTS 'FISCAL_CREDIT_01';

ALTER TYPE "InvoiceFiscalStatus" ADD VALUE IF NOT EXISTS 'LOCAL_ISSUED';
ALTER TYPE "InvoiceFiscalStatus" ADD VALUE IF NOT EXISTS 'LEGACY_UNVERIFIED';
